import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Head from "next/head";
import styles from "@/styles/cubifood.module.scss";
import CubiFoodPromotions from "@/components/CubiFoodPromotions";
import CubiFoodTopTreasures from "../components/CubiFoodTopTreasures";
import CubiFoodCategories from "@/components/CubiFoodCategories";

const CubiFood: React.FC<any> = () => {
  return (
    <>
      <Head>
        <title>CubiFood | Cubitech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cubifood.ico" />
      </Head>
      <main>
        {/* Starting block of CubiFood page */}
        <Box
          sx={{
            backgroundImage: `url('./cubifood/block1.png')`, // Replace with your image path
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center",
            height: "85vh",
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "flex-start",
            position: "relative", // Added position relative
            marginTop: "-75px",
          }}
        />

        {/* CubiFood slogan block */}
        <Box
          paddingX={"10%"}
          paddingY={"2.5%"}
          bgcolor={"#fff"}
          color={"#008573"}
          textAlign={"center"}
        >
          <Typography
            variant={"h5"}
            className={styles.merriWeather}
            fontStyle={"italic"}
            fontWeight={700}
            fontSize={32}
          >
            Eat Smart. Pay Easy. Enjoy Every Bite.
          </Typography>
        </Box>

        {/* CubiFood Promotions block */}
        <CubiFoodPromotions />

        {/* CubiFood Top Treasures block */}
        <CubiFoodTopTreasures />

        {/* CubiFood Top Treasures block */}
        <CubiFoodCategories />
      </main>
    </>
  );
};

export default CubiFood;
