import CubiMartBargainBlitz from "@/components/CubiMartBargainBlitz";
import CubiMartCategories from "@/components/CubiMartCategories";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Head from "next/head";

const CubiMart: React.FC<any> = () => {
  return (
    <>
      <Head>
        <title>CubiMart | Cubitech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cubitech.ico" />
      </Head>
      <main>
        {/* Starting block of CubiMart page */}
        <Box
          sx={{
            backgroundImage: `url('./cubimart/block1.png')`, // Replace with your image path
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center",
            // width: '80%',
            height: "60vh",
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "flex-start",
            position: "relative", // Added position relative
            marginTop: "-75px",
            // marginX: '10%'
          }}
        >
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "60vh",
              backgroundColor: "rgba(0, 0, 0, 0.3)", // Adjust the alpha value for transparency
            }}
          ></div>
          <Typography
            variant={"h1"}
            fontWeight={600}
            fontSize={54}
            color="white"
            style={{
              width: "80%",
              marginLeft: "10%",
              marginRight: "10%",
              marginTop: "275px",
              position: "relative",
              zIndex: 1,
            }}
          >
            Promotion Banner
          </Typography>
        </Box>

        {/* CubiMart Bargain Blitz block */}
        <CubiMartBargainBlitz />

        {/* CubiMart categories block */}
        <CubiMartCategories />
      </main>
    </>
  );
};

export default CubiMart;
