import CubiFoodPeekView from "@/components/CubiFoodPeekView";
import CubiMartPeekView from "@/components/CubiMartPeekView";
import WeeklyPromotions from "@/components/WeeklyPromotions";
import Avatar from "@mui/material/Avatar";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import Head from "next/head";
import Image from 'next/image'

const Index: React.FC<any> = () => {
   // Cubitech services avatar data
   const cubitechServicesAvatars = [
    {
      alt: "CubiFood",
      src: "./cubifood_light.svg",
      width: 213, // 1282
      height: 45, // 274
      marginRight: 2,
    },
    {
      alt: "CubiMart",
      src: "./cubimart_light.svg",
      width: 213, // 1282
      height: 45, // 274
      marginRight: 2,
    },
    {
      alt: "CubiRide",
      src: "./cubiride_light.svg",
      width: 213, // 1282
      height: 45, // 274
      marginRight: 2,
    },
    {
      alt: "CubiPerk",
      src: "./cubiperk_light.svg",
      width: 213, // 1282
      height: 45, // 274
      marginRight: 2,
    },
  ];

  return (
    <>
      <Head>
        <title>Cubitech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cubitech.ico" />
      </Head>
      <main>
        {/* Starting block of Index page */}
        <Box
          sx={{
            backgroundImage: `url('./index/block1.png')`, // Replace with your image path
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center bottom",
            height: "100vh",
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "flex-start",
            position: "relative", // Added position relative
            marginTop: "-75px",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              backgroundColor: "rgba(0, 0, 0, 0.3)", // Adjust the alpha value for transparency
            }}
          ></div>
          <Typography
            variant={"h1"}
            fontWeight={600}
            fontSize={54}
            color="white"
            style={{
              width: "80%",
              marginLeft: "10%",
              marginRight: "10%",
              marginTop: "500px",
              position: "relative",
              zIndex: 1,
            }}
          >
            Cubitech: Beyond Fintech,
            <br />
            Infinite Possibilities for Your Life!
          </Typography>
        </Box>

        {/* Cubitech services block */}
        <Box
          paddingX={"10%"}
          paddingY={"3%"}
          bgcolor={"primary.light"}
          textAlign={"center"}
        >
          <Typography
            variant={"h4"}
            color={"primary.main"}
            fontSize={36}
            fontWeight={600}
          >
            Our Services
          </Typography>
          <Typography
            variant={"h5"}
            color={"primary.main"}
            fontSize={26}
            fontWeight={500}
            marginY={"2%"}
          >
            One platform, countless solutions - from essentials to
            opportunities.
          </Typography>

          <div style={{ display: "flex", justifyContent: "center" }}>
            {cubitechServicesAvatars.map((avatar, index) => (
              <Avatar
                key={index} // Key should be unique, ideally use a unique identifier from your data
                alt={avatar.alt}
                src={avatar.src}
                component={"div"}
                sx={{
                  width: avatar.width,
                  height: avatar.height,
                  marginRight: avatar.marginRight,
                }}
                variant={"square"}
              />
            ))}
          </div>
        </Box>

        {/* Weekly Promotion block */}
        <WeeklyPromotions />

        {/* CubiFood Peek Menu block */}
        <CubiFoodPeekView />

        {/* CubiMart Peek Menu block */}
        <CubiMartPeekView />

        {/* CubiRide block */}
        <Box paddingX={"10%"} paddingY={"4%"}>
          <Grid container display={"flex"} alignItems={'center'}>
            <Grid item xs={6} textAlign={"left"}>
              <Image
                src="/index/block2.svg"
                width={475} // 1902
                height={226} // 906
                alt="JustCubi"
                style={{ display: "block" }}
              />
            </Grid>
            <Grid item xs={6}>
              <Typography
                variant={"h4"}
                fontWeight={600}
                fontSize={32}
                color={"primary.main"}
                sx={{ width: "85%", marginLeft: "15%" }}
              >
                Rushing off to somewhere?
                <br /> Let CubiRide take you to your destination!
              </Typography>
              <Typography
                sx={{ width: "85%", marginLeft: "15%", marginY: "3%" }}
                fontWeight={500}
                color={"primary.dark"}
                fontSize={18}
              >
                Elevate Your Journey: From CubiEconomy to CubiFirst Class
              </Typography>
              <div
                style={{
                  width: "85%",
                  marginLeft: "15%",
                }}
              >
                <Button variant={"contained"} size={"large"} color={"primary"}>
                  Book A Ride Now!
                </Button>
              </div>
            </Grid>
          </Grid>
        </Box>

        {/* CubiPerk block */}
        <Box paddingX={"10%"} paddingY={"4%"} bgcolor={"primary.light"}>
          <Grid container display={"flex"} alignItems={"center"}>
            <Grid item xs={6}>
              <Typography
                variant={"h4"}
                fontWeight={600}
                color={"primary.main"}
                sx={{ width: "85%", marginRight: "15%" }}
              >
                Get more from Cubitech!
                <br />
                Boost your points with our loyalty program.
              </Typography>
              <Typography
                sx={{ width: "85%", marginRight: "15%", marginY: "3%" }}
                fontWeight={500}
                color={"primary.dark"}
                fontSize={18}
              >
                Exchange your airline miles to CubiPerk points today!
              </Typography>
              <div
                style={{
                  width: "85%",
                  marginRight: "15%",
                  marginTop: "3%",
                }}
              >
                <Button
                  variant={"contained"}
                  size={"large"}
                  sx={{
                    bgcolor: "primary.dark",
                  }}
                >
                  Learn More
                </Button>
              </div>
            </Grid>
            <Grid item xs={6} display={"flex"} justifyContent={"flex-end"}>
              <Image
                src="/index/block3.svg"
                width={480} // 1920
                height={270} // 1080
                alt="CubiRewards"
              />
            </Grid>
          </Grid>
        </Box>
      </main>
    </>
  );
};

export default Index;
